<MenuWidget>:
    canvas:
        Color:
            rgba: .8, .8, .8, .5
        Rectangle:
            size: self.size

    Image:
        source: "images/title.png"
        pos_hint: {"center_x": .5, "center_y": .7}

    Button:
        text: "S T A R T"
        font_size: dp(60)
        size_hint: .5, .3
        pos_hint: {"center_x": .5, "center_y": .3}
        background_normal: ""
        background_color: 1, 1, 1, 0.1
        on_press: root.parent.start()
